server:
  domain: http://localhost:8888
  port: 8888
  servlet:
    context-path: /e-learning/api/v1

spring:
  profiles:
    active: secret
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguoihaihau2020@gmail.com
    password: wypp ayqa jtzi xcep
    from: E-Learning
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  datasource:
    url: jdbc:mariadb://localhost:3306/e-learning
    username: root
    password: namdinh1
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

client:
  oauth2-google-api:
    name: oauth2-google-api
    base-url: https://oauth2.googleapis.com
  media-service:
    name: media-service
    base-url: http://localhost:8081/e-learning/media-service/api/v1

jwt:
  signer-key: rrejrjgriheuihufeyugfyurejfdhbfefuhr4374bfbbejhjrfrefhrfrvv4838493
  valid-duration: 86400 # 24 * 60 * 60 -- seconds
  refresh-valid-duration: 172800 # 2 * 24 * 60 * 60 -- seconds

verify:
  time-valid: 300
  wait-between-sends: 60        # (seconds) thời gian chờ giữa mỗi lần gửi
  max-continuous-sends: 5       # số lần gửi liên tục tối đa
  continuous-window: 300        # (seconds) khoảng thời gian tính là "liên tục" (vd: 5 phút)

